version: "3.8"
services:
  web:
    build: .
    ports:
      - "5023:5023"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    restart: unless-stopped